### ISSUE TITLE
Verificar erros gerados nos testes de carga 250 usuários simultâneos 25/11

### ISSUE THREAD

**Issue by gBritz** [Famintus/WebPlataform#180]
Erros gerados em lt.elefanteletrado.com.br no teste com 250 usuários e 2000 iterações a partir das 11:39 do dia 25/11 com duração de 9 min e 30 seg.

Três erros para investigar:

__________________________________________
/lt.elefanteletrado.com.br/Reader/RedirectListen System.NullReferenceException

Error message
System.NullReferenceException: Object reference not set to an instance of an object.

Stack trace
at LiterateElephant.Web.Controllers.ReaderController.SetUrlForRedirecting() in c:\a\src\LiterateElephant.Web\LiterateElephant.Web\Controllers\ReaderController.cs:line 189
at LiterateElephant.Web.Controllers.ReaderController.RedirectListen(Boolean isMediaLoaded) in c:\a\src\LiterateElephant.Web\LiterateElephant.Web\Controllers\ReaderController.cs:line 66
at lambda_method(Closure , ControllerBase , Object[] )
at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)

__________________________________________

/lt.elefanteletrado.com.br/Quiz/QuizRedirect System.NullReferenceException

Error message
System.NullReferenceException: Object reference not set to an instance of an object.

Sample stack trace
at LiterateElephant.Web.Controllers.QuizController.SetUrlForRedirecting() in c:\a\src\LiterateElephant.Web\LiterateElephant.Web\Controllers\QuizController.cs:line 90
at LiterateElephant.Web.Controllers.QuizController.QuizRedirect(Boolean isMediaLoaded) in c:\a\src\LiterateElephant.Web\LiterateElephant.Web\Controllers\QuizController.cs:line 53
at lambda_method(Closure , ControllerBase , Object[] )
at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)

__________________________________________

/lt.elefanteletrado.com.br/Reader/Redirect System.NullReferenceException

Error message
System.NullReferenceException: Object reference not set to an instance of an object.

Sample stack trace
at LiterateElephant.Web.Controllers.ReaderController.SetUrlForRedirecting() in c:\a\src\LiterateElephant.Web\LiterateElephant.Web\Controllers\ReaderController.cs:line 189
at LiterateElephant.Web.Controllers.ReaderController.Redirect(Boolean isMediaLoaded) in c:\a\src\LiterateElephant.Web\LiterateElephant.Web\Controllers\ReaderController.cs:line 42
at lambda_method(Closure , ControllerBase , Object[] )
at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)

**Comment by gBritz** [comment]
**Status in Jira**
    Fabio Beckenkamp (fabio@elefanteletrado.com.br) `Created` at fabio@elefanteletrado.com.br

    Fabio Beckenkamp (fabio@elefanteletrado.com.br) set `In Progress` at 11/12/2014 10:22:12
    Fabio Beckenkamp (fabio@elefanteletrado.com.br) set `Closed` at 11/12/2014 10:22:12

**Comment by gBritz** [comment]
**Commentary** by Guilherme Britz (guilhermevideira@cwi.com.br)
Ocorre erro na requisição "abort" porque, na requisição anterior, está encerrando a sessão com o SignalR. A mensagem de erro informa que o token de conexão expirou.

Como solução provisória, reordenei as chamadas para encerrar a conexão após à requisição abort.
