### ISSUE TITLE
Desligar token de autenticação para os testes de carga

### ISSUE THREAD

**Issue by gBritz** [Famintus/WebPlataform#181]
Não conseguimos configurar o token de autenticação nos testes de carga. Com isto, dois erros estão sendo gerados nos testes. Vamos desabilitar o uso do token durante os testes para eliminar este erro dos resultados.
Abaixo os erros:

________________________________________
System.Web.Mvc.HttpAntiForgeryException
/lt.elefanteletrado.com.br/Account/AuthenticateStudent

Error message
System.Web.Mvc.HttpAntiForgeryException: The anti-forgery cookie token and form field token do not match.

Sample stack trace
at System.Web.Helpers.AntiXsrf.TokenValidator.ValidateTokens(HttpContextBase httpContext, IIdentity identity, AntiForgeryToken sessionToken, AntiForgeryToken fieldToken)
at System.Web.Helpers.AntiXsrf.AntiForgeryWorker.Validate(HttpContextBase httpContext)
at System.Web.Mvc.ControllerActionInvoker.InvokeAuthorizationFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__19(AsyncCallback asyncCallback, Object asyncState)

________________________________________
System.Web.Mvc.HttpAntiForgeryException
/lt.elefanteletrado.com.br/Account/Login

Error message
System.Web.Mvc.HttpAntiForgeryException: The anti-forgery cookie token and form field token do not match.

Sample stack trace
at System.Web.Helpers.AntiXsrf.TokenValidator.ValidateTokens(HttpContextBase httpContext, IIdentity identity, AntiForgeryToken sessionToken, AntiForgeryToken fieldToken)
at System.Web.Helpers.AntiXsrf.AntiForgeryWorker.Validate(HttpContextBase httpContext)
at System.Web.Mvc.ControllerActionInvoker.InvokeAuthorizationFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__19(AsyncCallback asyncCallback, Object asyncState)

**Comment by gBritz** [comment]
**Status in Jira**
    Fabio Beckenkamp (fabio@elefanteletrado.com.br) `Created` at fabio@elefanteletrado.com.br

    Fabio Beckenkamp (fabio@elefanteletrado.com.br) set `In Progress` at 11/12/2014 10:22:59
    Fabio Beckenkamp (fabio@elefanteletrado.com.br) set `Closed` at 11/12/2014 10:22:59
