### ISSUE TITLE
Analisar erro GetLiveReaderFilters

### ISSUE THREAD

**Issue by gBritz** [Famintus/WebPlataform#188]
System.Data.Entity.Core.EntityCommandExecutionException
/lt.elefanteletrado.com.br/Admin/Report/GetLiveReaderFilters

Error message
System.Data.Entity.Core.EntityCommandExecutionException: Transaction (Process ID 137) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

Stack trace
[SqlException: Transaction (Process ID 137) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.]
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
at System.Data.SqlClient.SqlDataReader.Read()
at Glimpse.Ado.AlternateType.GlimpseDbDataReader.Read()
at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.StoreRead()

[EntityCommandExecutionException: An error occurred while reading from the store provider's data reader. See the inner exception for details.]
at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.HandleReaderException(Exception e)
at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.StoreRead()
at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.SimpleEnumerator.MoveNext()
at LiterateElephant.Controller.UserController.LiveUsersInternal() in c:\TFS\ElefanteLetrado\Portal\trunk\LiterateElephant\LiterateElephant.Controller\UserController.cs:line 1111
at LiterateElephant.Controller.UserController.LiveUsers(Nullable`1 schoolId, Nullable`1 teacherId, Boolean isStudent) in c:\TFS\ElefanteLetrado\Portal\trunk\LiterateElephant\LiterateElephant.Controller\UserController.cs:line 659
at LiterateElephant.Web.Areas.Admin.Controllers.ReportController.GetLiveReaderFilters() in c:\TFS\ElefanteLetrado\Portal\trunk\LiterateElephant\LiterateElephant.Web\LiterateElephant.Web\Areas\Admin\Controllers\ReportController.cs:line 110
at lambda_method(Closure , ControllerBase , Object[] )
at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)

**Comment by gBritz** [comment]
**Status in Jira**
    Fabio Beckenkamp (fabio@elefanteletrado.com.br) `Created` at fabio@elefanteletrado.com.br

    Fabio Beckenkamp (fabio@elefanteletrado.com.br) set `In Progress` at 11/12/2014 11:37:12
    Fabio Beckenkamp (fabio@elefanteletrado.com.br) set `Closed` at 11/12/2014 11:37:12
