### ISSUE TITLE
Analisar erro no GetLiveReaderFilter

### ISSUE THREAD

**Issue by gBritz** [Famintus/WebPlataform#189]
System.Web.HttpException
/lt.elefanteletrado.com.br/Admin/Report/GetLiveReaderFilter

Error message
System.Web.HttpException: Um método 'GetLiveReaderFilter' de ação pública não foi encontrado no controlador 'LiterateElephant.Web.Areas.Admin.Controllers.ReportController'.

Stack trace
at System.Web.Mvc.Controller.HandleUnknownAction(String actionName)
at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by gBritz** [comment]
**Status in Jira**
    Fabio Beckenkamp (fabio@elefanteletrado.com.br) `Created` at fabio@elefanteletrado.com.br

    Fabio Beckenkamp (fabio@elefanteletrado.com.br) set `In Progress` at 11/12/2014 10:24:38
    Fabio Beckenkamp (fabio@elefanteletrado.com.br) set `Closed` at 11/12/2014 10:24:38

**Comment by gBritz** [comment]
**Commentary** by Guilherme Britz (guilhermevideira@cwi.com.br)
Não existe método "GetLiveReaderFilter" na controller "Admin/Report" e acredito que devia ter sido algum teste errado apontando para esse nome.

Após esse erro, executamos 3 vezes os testes (27/11/2014) e não apareceu esse erro.

Vou considerar como corrigido.
