### ISSUE TITLE
Analisar erro no GetRostersForTeacher

### ISSUE THREAD

**Issue by gBritz** [Famintus/WebPlataform#190]
System.Data.Entity.Core.EntityCommandExecutionException
/lt.elefanteletrado.com.br/Admin/Roster/GetRostersForTeacher

Error message
System.Data.Entity.Core.EntityCommandExecutionException: Transaction (Process ID 165) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

Stack trace
[SqlException: Transaction (Process ID 165) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.]
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
at System.Data.SqlClient.SqlDataReader.Read()
at Glimpse.Ado.AlternateType.GlimpseDbDataReader.Read()
at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.StoreRead()

[EntityCommandExecutionException: An error occurred while reading from the store provider's data reader. See the inner exception for details.]
at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.HandleReaderException(Exception e)
at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.StoreRead()
at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.RowNestedResultEnumerator.MoveNext()
at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.ObjectQueryNestedEnumerator.TryReadToNextElement()
at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.ObjectQueryNestedEnumerator.MoveNext()
at LiterateElephant.Controller.UserController.TimeSpentOnlineByUsers(Nullable`1 fromDate, Nullable`1 toDate, Nullable`1 userId, Nullable`1 schoolId, Nullable`1 teacherId, Boolean isStudent) in c:\TFS\ElefanteLetrado\Portal\trunk\LiterateElephant\LiterateElephant.Controller\UserController.cs:line 755
at LiterateElephant.Behaviors.UserService.TimeSpentOnlineByUsers(Nullable`1 fromDate, Nullable`1 toDate, Nullable`1 userId, Nullable`1 schoolId, Nullable`1 teacherId, Boolean isStudent) in c:\TFS\ElefanteLetrado\Portal\trunk\LiterateElephant\LiterateElephant.Behaviors\UserService.cs:line 270
at LiterateElephant.Web.Areas.Admin.Controllers.RosterController.<GetCourseForTeacher>b__6b(Student student) in c:\TFS\ElefanteLetrado\Portal\trunk\LiterateElephant\LiterateElephant.Web\LiterateElephant.Web\Areas\Admin\Controllers\RosterController.cs:line 1711
at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
at LiterateElephant.Web.Areas.Admin.Controllers.RosterController.GetCourseForTeacher(Int32 rosterId, List`1& users, Int32& returnStatus) in c:\TFS\ElefanteLetrado\Portal\trunk\LiterateElephant\LiterateElephant.Web\LiterateElephant.Web\Areas\Admin\Controllers\RosterController.cs:line 1744
at LiterateElephant.Web.Areas.Admin.Controllers.RosterController.GetRostersForTeacher(String teacherName, Int32 teacherId, Boolean parentRoster, Int32 studentId, Boolean isFromReport) in c:\TFS\ElefanteLetrado\Portal\trunk\LiterateElephant\LiterateElephant.Web\LiterateElephant.Web\Areas\Admin\Controllers\RosterController.cs:line 359
at lambda_method(Closure , ControllerBase , Object[] )
at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)

**Comment by gBritz** [comment]
**Status in Jira**
    Fabio Beckenkamp (fabio@elefanteletrado.com.br) `Created` at fabio@elefanteletrado.com.br

    Fabio Beckenkamp (fabio@elefanteletrado.com.br) set `In Progress` at 11/12/2014 11:37:20
    Fabio Beckenkamp (fabio@elefanteletrado.com.br) set `Closed` at 11/12/2014 11:37:20
