### ISSUE TITLE
Ocorre erro "NullReferenceException" em "DescriptorReport"

### ISSUE THREAD

**Issue by gBritz** [Famintus/WebPlataform#196]
Link: https://rpm.newrelic.com/accounts/809247/applications/11841789/traced_errors/2492199991

at ASP._Page_Areas_Admin_Views_Dashboard_DescriptorReport_cshtml.<Execute>b__30(LegacyModule m) in d:\qa\Areas\Admin\Views\Dashboard\DescriptorReport.cshtml:line 14
at System.Collections.Generic.List`1.Find(Predicate`1 match)
at ASP._Page_Areas_Admin_Views_Dashboard_DescriptorReport_cshtml.Execute() in d:\qa\Areas\Admin\Views\Dashboard\DescriptorReport.cshtml:line 14
at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
at System.Web.WebPages.StartPage.ExecutePageHierarchy()
at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)

**Comment by gBritz** [comment]
**Status in Jira**
    Guilherme Britz (guilhermevideira@cwi.com.br) `Created` at guilhermevideira@cwi.com.br

    Fabio Beckenkamp (fabio@elefanteletrado.com.br) set `In Progress` at 11/12/2014 10:32:41
    Fabio Beckenkamp (fabio@elefanteletrado.com.br) set `Closed` at 11/12/2014 10:32:41

**Comment by gBritz** [comment]
**Commentary** by Guilherme Britz (guilhermevideira@cwi.com.br)
Foi aplicado solução, rodado os testes de performance e não acusou erro.
