### ISSUE TITLE
Analisar erros no GetRostersForTeacher

### ISSUE THREAD

**Issue by gBritz** [Famintus/WebPlataform#197]
Atenção que são dois erros abaixo:

______________________
System.Web.HttpException
/lt.elefanteletrado.com.br/Admin/Roster/GetRostersForTeacher

Error message
System.Web.HttpException: Request timed out.

______________________
System.Data.Entity.Core.EntityCommandExecutionException
/lt.elefanteletrado.com.br/Admin/Roster/GetRostersForTeacher

Error message
System.Data.Entity.Core.EntityCommandExecutionException: The wait operation timed out

Sample stack trace
[Win32Exception: The wait operation timed out]

[SqlException: Timeout expired. The timeout period elapsed prior to completion of the operation or the server is not responding.]
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
at System.Data.SqlClient.SqlDataReader.TrySetMetaData(_SqlMetaDataSet metaData, Boolean moreInfo)
at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
at System.Data.SqlClient.SqlDataReader.get_MetaData()
at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
at Glimpse.Ado.AlternateType.GlimpseDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)

[EntityCommandExecutionException: An error occurred while executing the command definition. See the inner exception for details.]
at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
at LiterateElephant.Controller.UserController.TimeSpentOnlineByUsersInternal(Nullable`1 fromDate, Nullable`1 toDate, Nullable`1 userId, Nullable`1 schoolId, Nullable`1 teacherId, Boolean isStudent) in c:\CWI\ElefanteLetrado\trunk\LiterateElephant\LiterateElephant.Controller\UserController.cs:line 1141
at LiterateElephant.Controller.UserController.TimeSpentOnlineByUsers(Nullable`1 fromDate, Nullable`1 toDate, Nullable`1 userId, Nullable`1 schoolId, Nullable`1 teacherId, Boolean isStudent) in c:\CWI\ElefanteLetrado\trunk\LiterateElephant\LiterateElephant.Controller\UserController.cs:line 709
at LiterateElephant.Behaviors.UserService.TimeSpentOnlineByUsers(Nullable`1 fromDate, Nullable`1 toDate, Nullable`1 userId, Nullable`1 schoolId, Nullable`1 teacherId, Boolean isStudent) in c:\CWI\ElefanteLetrado\trunk\LiterateElephant\LiterateElephant.Behaviors\UserService.cs:line 270
at LiterateElephant.Web.Areas.Admin.Controllers.RosterController.<GetCourseForTeacher>b__6b(Student student) in c:\CWI\ElefanteLetrado\trunk\LiterateElephant\LiterateElephant.Web\LiterateElephant.Web\Areas\Admin\Controllers\RosterController.cs:line 1711
at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
at LiterateElephant.Web.Areas.Admin.Controllers.RosterController.GetCourseForTeacher(Int32 rosterId, List`1& users, Int32& returnStatus) in c:\CWI\ElefanteLetrado\trunk\LiterateElephant\LiterateElephant.Web\LiterateElephant.Web\Areas\Admin\Controllers\RosterController.cs:line 1744
at LiterateElephant.Web.Areas.Admin.Controllers.RosterController.GetRostersForTeacher(String teacherName, Int32 teacherId, Boolean parentRoster, Int32 studentId, Boolean isFromReport) in c:\CWI\ElefanteLetrado\trunk\LiterateElephant\LiterateElephant.Web\LiterateElephant.Web\Areas\Admin\Controllers\RosterController.cs:line 359
at lambda_method(Closure , ControllerBase , Object[] )
at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)

**Comment by gBritz** [comment]
**Status in Jira**
    Fabio Beckenkamp (fabio@elefanteletrado.com.br) `Created` at fabio@elefanteletrado.com.br

    Fabio Beckenkamp (fabio@elefanteletrado.com.br) set `In Progress` at 11/12/2014 11:37:32
    Fabio Beckenkamp (fabio@elefanteletrado.com.br) set `Closed` at 11/12/2014 11:37:32
