### ISSUE TITLE
Erro no relatório de descritores essenciais para usuários sem estudantes

### ISSUE THREAD

**Issue by gBritz** [Famintus/WebPlataform#256]
https://rpm.newrelic.com/accounts/809247/applications/12046049/traced_errors/2649966714

SINTOMA: Erro é gerado no relatório de descritores essenciais para pais e usuários domésticos SEM estudantes cadastrados.

Passos para reproduzir (QA):

1) Logar com usuário doméstico "bernardobrezende+teste11122014@gmail.com". Senha "123456zz"
2) Na dashboard, rolar até o rodapé da página em "Descritores essenciais".

**Comment by gBritz** [comment]
**Status in Jira**
    Bernardo Bosak de Rezende (bernardobosak@cwi.com.br) `Created` at bernardobosak@cwi.com.br

    Fabio Beckenkamp (fabio@elefanteletrado.com.br) set `In Progress` at 19/01/2015 02:08:46
    Fabio Beckenkamp (fabio@elefanteletrado.com.br) set `Closed` at 19/01/2015 02:08:46

**Comment by gBritz** [comment]
**Commentary** by Bernardo Bosak de Rezende (bernardobosak@cwi.com.br)
Pré-análise:

- A função GetDescriptorReport (IndividualDashboard.cshtml e ParentDashboard.cshtml) recebe um studentId por parâmetro. Para estes usuários sem estudantes o id está undefined.
- O id do estudante estando undefined gera erro no ModelBinder do ASP.NET MVC, pois na Action GetDescriptorReportForParent do DashboardController o studentId é int, e não int? (inteiro nulável)

Seguindo o padrão dos outros relatórios, é preciso apenas:

- Corrigir o model bind no parâmetro da Action (trocando de int para int?)
- *(OPCIONAL)* Colocar uma condicional para executar as consultas deste relatório apenas se o id estiver definido. Pode ser uma pequena otimização.

**Comment by gBritz** [comment]
**Commentary** by Fabio Beckenkamp (fabio@elefanteletrado.com.br)
O erro reportado não foi visto, mas outro erro foi gerado no NR:
https://rpm.newrelic.com/accounts/809247/applications/12046049/traced_errors/2684929132

Trace:

System.ArgumentException
/qa.elefanteletrado.com.br/Admin/Dashboard/GetKidsQuickStats

18:13:37
TIME
WIN-QA-20041217(ROOT:qaEL QA - AWS)
INSTANCE
1
COUNT
Error message
System.ArgumentException: O dicionário de parâmetros contém uma entrada nula para o parâmetro 'studentId' de tipo que não permite valor anulável 'System.Int32' para o método 'System.Web.Mvc.ActionResult GetKidsQuickStats(Int32)' em 'LiterateElephant.Web.Areas.Admin.Controllers.DashboardController'. Um parâmetro opcional deve ser um tipo de referência, um tipo que permite valor anulável ou declarado como opcional. Parameter name: parameters

Stack trace
at System.Web.Mvc.ActionDescriptor.ExtractParameterFromDictionary(ParameterInfo parameterInfo, IDictionary`2 parameters, MethodInfo methodInfo)
at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)

**Comment by gBritz** [comment]
**Commentary** by Natã Barbosa (natambarbosa@gmail.com)
Erro corrigido seguindo as sugestões do Bernardo, inclusive a sugestão opcional para evitar requisições com argumentos inválidos.

Além disso, outro erro que estava aparecendo no console JavaScript foi corrigido.

**Comment by gBritz** [comment]
**Commentary** by Natã Barbosa (natambarbosa@gmail.com)
Fabio, 

A raíz do problema é provavelmente a mesma (requisições com argumentos nulos sendo enviadas para o servidor, e sem tratamento de argumento inválido no servidor), porém os relatórios e funcionalidades são diferentes.

Abraço.

**Comment by gBritz** [comment]
**Commentary** by Fabio Beckenkamp (fabio@elefanteletrado.com.br)
Verificar novo erro encontrado, analisar se deve ser tratado ainda neste bug ou abrir um novo.

**Comment by gBritz** [comment]
**Commentary** by Natã Barbosa (natambarbosa@gmail.com)
Fabio,

Por favor, quando abrir, descreva de forma genérica que precisamos fazer este tratamento para os relatórios, quando não houver nenhum estudante cadastrado. Acredito que isto seja necessário após conferir há alguns instantes que várias funções na página tem a mesma característica.

Abraço.

**Comment by gBritz** [comment]
**Commentary** by Fabio Beckenkamp (fabio@elefanteletrado.com.br)
OK, então pode colocar como resolvida esta aqui novamente que vou abrir outra issue para este bug.

**Comment by gBritz** [comment]
**Commentary** by Fabio Beckenkamp (fabio@elefanteletrado.com.br)
Aprovado em QA
