### ISSUE TITLE
Usuário - remoção de usuário dá erro na segunda tentativa de remover

### ISSUE THREAD

**Issue by gBritz** [Famintus/WebPlataform#260]
1) Pesquisar usuários não removidos
2) Selecionar um usuário e remover (clicar na lixeira na lista de usuários).
3) Pesquisa por usuários removidos
4) Seleciona o mesmo usuário removido anteriormente e reativa o usuário (seta de loop quadrado na lista de usuário).
5) Repete o processo do passo 1. Ao tentar remover novamente o usuário, ocorre um erro de banco de dados.

Erro capturado no New Relic:
Error message
System.Data.Entity.Validation.DbEntityValidationException: Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.

Stack trace
at System.Data.Entity.Internal.InternalContext.SaveChanges()
at LiterateElephant.Data.LiterateElephantContext.SaveChanges() in c:\a\src\LiterateElephant.Data\LiterateElephantContext.cs:line 181
at LiterateElephant.Controller.UserController.AddUserEvent(Int32 userId, UserEventType userEventType, String updateState) in c:\a\src\LiterateElephant.Controller\UserController.cs:line 711
at LiterateElephant.Controller.UserController.SoftDeleteUser(Int32 userId, Int32 auditUserId) in c:\a\src\LiterateElephant.Controller\UserController.cs:line 558
at LiterateElephant.Web.Areas.Admin.Controllers.UserController.Delete(Int32 userId) in c:\a\src\LiterateElephant.Web\LiterateElephant.Web\Areas\Admin\Controllers\UserController.cs:line 193
at lambda_method(Closure , ControllerBase , Object[] )
at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)

**Comment by gBritz** [comment]
**Status in Jira**
    Fabio Beckenkamp (fabio@elefanteletrado.com.br) `Created` at fabio@elefanteletrado.com.br

    Fabio Beckenkamp (fabio@elefanteletrado.com.br) set `In Progress` at 19/01/2015 02:15:57
    Fabio Beckenkamp (fabio@elefanteletrado.com.br) set `Closed` at 19/01/2015 02:15:57

**Comment by gBritz** [comment]
**Commentary** by Raphael Vilvert (rvilvert@outlook.com)
é o mesmo DbEntityValidationException da YAA-225

**Comment by gBritz** [comment]
**Commentary** by Raphael Vilvert (rvilvert@outlook.com)
neste caso ele adicionou o timestamp duas vezes ao nome do usuário, assim estourou o campo... vou investigar a necessidade do timestamp.

**Comment by gBritz** [comment]
**Commentary** by Raphael Vilvert (rvilvert@outlook.com)
Resolvido como parte da YAA-225

**Comment by gBritz** [comment]
**Commentary** by Fabio Beckenkamp (fabio@elefanteletrado.com.br)
Aprovado em QA
